version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: <RDS-ENDPOINT>:3306
      WORDPRESS_DB_USER: <RDS-USER>
      WORDPRESS_DB_PASSWORD: <RDS-PASSWORD>
      WORDPRESS_DB_NAME: <RDS-DATABASE>
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=<EFS-ENDPOINT>,rw"
      device: ":/"

networks:
  wordpress-network:
