version: '3.9'

services:
  nginx1:
    image: nginx:latest
    ports:
      - "8081:80"
    deploy:
      replicas: 2
    volumes:
      - nfs_volume:/usr/share/nginx/html
    networks:
      - nginx-network

volumes:
  nfs_volume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=<nfs-server-ip>,rw"
      device: ":/srv/nfs/shared"

networks:
  nginx-network:
    driver: overlay
