version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=<EFS-ENDPOINT>,rw"  # Substitua <EFS-ENDPOINT> pelo endpoint do seu EFS
      device: ":/"

networks:
  wordpress-network:
